version: '3'
services:
  postgres:
    image: data-exercise/local-postgres
    build:
      context: ./Docker
      dockerfile: Exercise-Postgres-Dockerfile
    user: postgres
    ports:
      - "5435:5432"